import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { DatabaseSync } from 'node:sqlite';
import { brokenLinks } from '../queries/broken-links.js';
import { missingFrontmatter } from '../queries/missing-frontmatter.js';
import { repoSizeReport } from '../queries/repo-size-report.js';
import { unusedAssets } from '../queries/unused-assets.js';

export function writeMarkdownReport(db: DatabaseSync, repoRoot: string, reportPath: string): string {
  const nodeCounts = countBy(db, 'nodes');
  const edgeCounts = countBy(db, 'edges');
  const size = repoSizeReport(db);
  const missing = missingFrontmatter(db, repoRoot);
  const broken = brokenLinks(db);
  const unused = unusedAssets(db, 75);

  const markdown = [
    '# Project Knowledge Graph Report',
    '',
    `Generated: ${new Date().toISOString()}`,
    '',
    '## Summary',
    '',
    `- Total files in graph: ${size.totalFiles}`,
    `- Total indexed bytes: ${formatBytes(size.totalBytes)}`,
    `- Node types: ${Object.keys(nodeCounts).length}`,
    `- Edge types: ${Object.keys(edgeCounts).length}`,
    '',
    '## Node Counts',
    '',
    table(['Type', 'Count'], Object.entries(nodeCounts).map(([type, count]) => [type, String(count)])),
    '',
    '## Edge Counts',
    '',
    table(['Type', 'Count'], Object.entries(edgeCounts).map(([type, count]) => [type, String(count)])),
    '',
    '## Largest Folders',
    '',
    table(['Folder', 'Size'], size.largestFolders.slice(0, 15).map((row) => [row.path, formatBytes(row.size)])),
    '',
    '## Largest Files',
    '',
    table(['File', 'Size'], size.largestFiles.slice(0, 15).map((row) => [row.path, formatBytes(row.size)])),
    '',
    '## Missing Frontmatter',
    '',
    missing.length
      ? table(['Path', 'Missing Fields'], missing.slice(0, 100).map((row) => [row.path, row.missing.join(', ')]))
      : 'No missing required frontmatter detected by the MVP rules.',
    '',
    '## Broken Internal Links',
    '',
    broken.length
      ? table(['Path', 'Line', 'Href'], broken.slice(0, 100).map((row) => [row.path ?? '', String(row.line ?? ''), row.href ?? row.message]))
      : 'No broken internal links detected by the graph scan.',
    '',
    '## Unused Assets',
    '',
    unused.length
      ? table(['Asset', 'Size'], unused.slice(0, 75).map((row) => [row.path, formatBytes(row.size)]))
      : 'No unused inspected assets detected.',
    '',
    '## Risky / Generated Folders',
    '',
    '- Runtime graph data lives in `.kg/` and should not be committed.',
    '- `public/pagefind/`, `.astro/`, `dist/`, and `dist-fast/` are generated and should not be manually edited.',
    '- `public/og/` is generated by the site OG pipeline; inspect changes before staging.',
    '- `src/data/_meta/` and `src/data/logo-manifest.json` may be generated by scripts.',
    size.riskyGeneratedFolders.length ? `- Large generated folders seen in the scan: ${size.riskyGeneratedFolders.join(', ')}` : '- No large ignored generated folders were indexed.',
    '',
    '## Suggested Cleanup',
    '',
    '- Review unused assets before deleting anything; dynamic Astro routes may reference some assets by convention.',
    '- Fix broken internal links before broad content migrations.',
    '- Keep source content in `src/content/`; do not edit retired legacy backup folders.',
    '',
    '## Suggested Next Graph Features',
    '',
    '- Add AST-based TypeScript and Astro parsing for more precise imports.',
    '- Add route-to-content resolution using Astro collection metadata.',
    '- Export graph slices to JSON for a future dashboard in `apps/kg-dashboard/`.',
    '- Add embeddings in `.kg/embeddings/` for semantic code/content search.',
    '',
  ].join('\n');

  mkdirSync(path.dirname(reportPath), { recursive: true });
  writeFileSync(reportPath, markdown);
  return reportPath;
}

function countBy(db: DatabaseSync, tableName: 'nodes' | 'edges'): Record<string, number> {
  const rows = db.prepare(`SELECT type, COUNT(*) AS count FROM ${tableName} GROUP BY type ORDER BY type`).all() as Array<{ type: string; count: number }>;
  return Object.fromEntries(rows.map((row) => [row.type, row.count]));
}

function table(headers: string[], rows: string[][]): string {
  if (!rows.length) return '';
  return [
    `| ${headers.join(' | ')} |`,
    `| ${headers.map(() => '---').join(' | ')} |`,
    ...rows.map((row) => `| ${row.map((cell) => String(cell).replace(/\|/g, '\\|')).join(' | ')} |`),
  ].join('\n');
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)} MB`;
  return `${(bytes / 1024 / 1024 / 1024).toFixed(1)} GB`;
}
